---
name: Test
on:
  push:
    branches:
      - master
      - ng-b4ns
      - release/**
  pull_request: null
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: sudo apt-get update && sudo apt-get install -y libseccomp-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.49.0
          args: --verbose
  ubuntu-2204-on-lxc:
    name: Ubuntu 22.04 on LXC
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3.0.2
      #- name: install lxd (v5.19)
      #  run: sudo snap remove --purge lxd && sudo snap install lxd --revision=26093
      - name: configure lxd
        run: cat test/lxd.yaml | sudo lxd init --preseed && sudo sysctl -w net.ipv4.ip_forward=1
      # thanks to https://andreas.scherbaum.la/post/2023-01-18_fix-lxc-network-issues-in-ubuntu-22.04/
      - name: Disable Docker Firewall 1
        run: sudo iptables -I DOCKER-USER -i lxdbr0 -o eth0 -j ACCEPT
      - name: Disable Docker Firewall 2
        run: sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      - name: debug
        run: sudo lxc network list && sudo iptables -t nat -L && sudo ufw status &&  sudo nft list table inet lxd
      - name: launch lxc container
        run: ./launch_test_lxc.sh
      - name: install dependencies and build
        run: sudo lxc exec test -- sudo --login --user ubuntu /host/test/init_test.sh
      - name: run tests
        run: sudo lxc exec test -- sudo --login --user ubuntu /home/ubuntu/bypass4netns/test/run_test.sh
      - name: benchmark (redis)
        run: sudo lxc exec test -- sudo --login --user ubuntu /home/ubuntu/bypass4netns/benchmark/redis.sh

