---
name: Test
on:
  push:
    branches:
      - master
      - ng-b4ns
      - release/**
  pull_request: null
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: sudo apt-get update && sudo apt-get install -y libseccomp-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.55.2
          args: --verbose

  create-lxc-image:
    name: create-lxc-image
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
         key: lxc-image-base-${{ hashFiles('go.sum', 'test/init_test.sh') }}
         path: /tmp/test-image.tar.zst
         lookup-only: true

      - name: setup lxd (v5.19)
        id: s1
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: ./setup_lxd.sh

      - name: launch lxc container
        id: s6
        if: steps.s1.conclusion == 'success'
        run: ./launch_test_lxc.sh

      - name: install dependencies and build
        id: s7
        if: steps.s6.conclusion == 'success'
        run: sudo lxc exec test -- sudo --login --user ubuntu /host/test/init_test.sh

      - name: export image
        id: s8
        if: steps.s7.conclusion == 'success'
        run: ./export_lxc_image.sh test

      - uses: actions/cache/save@v3
        id: s11
        if: steps.s8.conclusion == 'success'
        with:
          key: lxc-image-base-${{ hashFiles('go.sum', 'test/init_test.sh') }}
          path: /tmp/test-image.tar.zst

  test:
    runs-on: ubuntu-22.04
    needs: create-lxc-image
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - name: setup lxd (v5.19)
        run: ./setup_lxd.sh
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
         key: lxc-image-base-${{ hashFiles('go.sum', 'test/init_test.sh') }}
         path: /tmp/test-image.tar.zst
         fail-on-cache-miss: true
      - name: load lxc image
        run: sudo lxc image import /tmp/test-image.tar.zst --alias test-export
      - name: launch lxc container
        run: ./launch_test_lxc.sh test-export
      - run: sudo lxc exec test -- sudo --login --user ubuntu systemctl --user start containerd-fuse-overlayfs.service
      - run: sudo lxc exec test -- sudo --login --user ubuntu systemctl --user status --no-pager containerd-fuse-overlayfs.service
      - name: run test
        run: sudo lxc exec test -- sudo --login --user ubuntu /bin/bash -c "sleep 3 && /home/ubuntu/bypass4netns/test/run_test.sh"
      # some source codes may be updated. re-export new image.
      - name: export image
        run: sudo lxc image alias delete test-export && rm -f /tmp/test-image.tar.zst && ./export_lxc_image.sh test
      - uses: actions/cache/save@v3
        with:
          key: lxc-image-${{ github.sha }}
          path: /tmp/test-image.tar.zst
      #- name: debug
      #  run: ./debug.sh

  benchmark:
    runs-on: ubuntu-22.04
    needs: test
    timeout-minutes: 20
    strategy:
      matrix:
        script: ["iperf3_host", "iperf3", "postgres", "redis"]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: setup lxd (v5.19)
        run: ./setup_lxd.sh
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
         key: lxc-image-${{ github.sha }}
         path: /tmp/test-image.tar.zst
         fail-on-cache-miss: true
      - name: load lxc image
        run: sudo lxc image import /tmp/test-image.tar.zst --alias test-export
      - name: launch lxc container
        run: ./launch_test_lxc.sh test-export
      - run: sudo lxc exec test -- sudo --login --user ubuntu systemctl --user start containerd-fuse-overlayfs.service
      - run: sudo lxc exec test -- sudo --login --user ubuntu systemctl --user status --no-pager containerd-fuse-overlayfs.service
      - name: run benchmark (${{ matrix.script }})
        run: sudo lxc exec test -- sudo --login --user ubuntu /bin/bash -c "sleep 3 && /home/ubuntu/bypass4netns/benchmark/${{ matrix.script }}.sh"
      - name: upload plot
        id: get_plot
        if: matrix.script != 'iperf3_host'
        run: |
          mkdir /tmp/benchmark-results
          sudo lxc file pull test/home/ubuntu/bypass4netns/benchmark/${{ matrix.script }}-wo-b4ns-direct.log /tmp/benchmark-results/.
          sudo lxc file pull test/home/ubuntu/bypass4netns/benchmark/${{ matrix.script }}-wo-b4ns-host.log /tmp/benchmark-results/.
          sudo lxc file pull test/home/ubuntu/bypass4netns/benchmark/${{ matrix.script }}-w-b4ns.log /tmp/benchmark-results/.
      - uses: actions/upload-artifact@v3
        if: steps.get_plot.conclusion == 'success'
        with:
          name: benchmark-results
          path: /tmp/benchmark-results


  benchmark-multinode:
    runs-on: ubuntu-22.04
    needs: test
    timeout-minutes: 20
    strategy:
      matrix:
        script: ["iperf3", "postgres", "redis"]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: setup lxd (v5.19)
        run: ./setup_lxd.sh
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
         key: lxc-image-${{ github.sha }}
         path: /tmp/test-image.tar.zst
         fail-on-cache-miss: true
      - name: load lxc image
        run: sudo lxc image import /tmp/test-image.tar.zst --alias test-export
      - name: launch lxc container
        run: ./launch_test_lxc.sh test-export
      - run: sudo lxc exec test -- sudo --login --user ubuntu systemctl --user start containerd-fuse-overlayfs.service
      - run: sudo lxc exec test -- sudo --login --user ubuntu systemctl --user status --no-pager containerd-fuse-overlayfs.service
      - name: run benchmark (${{ matrix.script }})
        run: ./benchmark/${{ matrix.script }}_multinode.sh
      - name: upload plot
        run: |
          mkdir /tmp/benchmark-results
          cp benchmark/${{ matrix.script }}-multinode-wo-b4ns.log /tmp/benchmark-results/.
          cp benchmark/${{ matrix.script }}-multinode-w-b4ns.log /tmp/benchmark-results/.
      - uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: /tmp/benchmark-results
  
  plot:
    runs-on: ubuntu-22.04
    needs: [benchmark, benchmark-multinode]
    steps:
      - uses: actions/checkout@v4.1.1
      - run: sudo apt update && sudo apt install python3 python3-pip
      - run: pip3 install matplotlib numpy
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-results
          path: ./
      - run: mkdir /tmp/benchmark-plots
      - run: python3 benchmark/redis_plot.py redis-wo-b4ns-direct.log redis-wo-b4ns-host.log redis-multinode-wo-b4ns.log redis-w-b4ns.log redis-multinode-w-b4ns.log /tmp/benchmark-plots/redis.png
      - run: python3 benchmark/iperf3_plot.py iperf3-wo-b4ns-direct.log iperf3-wo-b4ns-host.log iperf3-multinode-wo-b4ns.log iperf3-w-b4ns.log iperf3-multinode-w-b4ns.log /tmp/benchmark-plots/iperf3.png
      - run: python3 benchmark/postgres_plot.py postgres-wo-b4ns-direct.log postgres-wo-b4ns-host.log postgres-multinode-wo-b4ns.log postgres-w-b4ns.log postgres-multinode-w-b4ns.log /tmp/benchmark-plots/postgres.png
      - uses: actions/upload-artifact@v3
        with:
          name: benchmark-plots
          path: /tmp/benchmark-plots
